title: Practice Problems
email: smajhi@berkeley.edu
baseurl: "/practice_problems"
url: "https://mids-w203.github.io"
github_username:  sushovan4

# Build settings
theme: minima
plugins:
  - jekyll-feed 

collections:
  categories:
    output: true
    sort_by: number
  problems:
    output: true
  references:
  
defaults:
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: category
  -
    scope:
      path: ""
      type: "problems"
    values:
      topic: 1000