title: Practice Problems
email: smajhi@berkeley.edu
baseurl: "/practice_problems"
url: "https://mids-w203.github.io/practice_problems"
github_username:  sushovan4
markdown: GFM

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
comments:
  provider:            giscus

giscus:
  repo:                "mids-w203/practice_problems"
  repo-id:             "MDEwOlJlcG9zaXRvcnkzMjIzNjQwMDk="
  category:            "General"
  category-id:         "DIC_kwDOEzbiac4CUBQk"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "light"
  crossorigin:         "anonymous"

# Build settings
theme: minima
plugins:
  - jekyll-feed 

collections:
  categories:
    output: true
    sort_by: index
  problems:
    output: true
    sort_by: title
  levels:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: category
  -
    scope:
      path: ""
      type: "problems"
    values:
      layout: problem
      level: 0
      index: 1000
