version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - '.:/usr/src/app'  
    ports:
      - 4000:4000
      - 35729:35729
    command: bundle exec jekyll serve -H 0.0.0.0 -l  -P 4000 --livereload
    