# https://letsencrypt.org/docs/certificates-for-localhost/
version: "3.3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: rails s -b 'ssl://0.0.0.0:3000?key=.ssh/localhost.key&cert=.ssh/localhost.crt'
    volumes:
      - '.:/usr/src/app'
    environment: 
      SLACK_CLIENT_ID: ''
      SLACK_CLIENT_SECRET: ''
      SLACK_API_TOKEN: ''
      SLACK_CHANNEL: 'C023GE5M47L'
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: w203
      POSTGRES_PASSWORD: w203
      POSTGRES_DB: w203_development
    volumes:
      - w203-db:/var/lib/postgresql/data

volumes:
  w203-db:
